- name: onepassword | apt key
  ansible.builtin.get_url:
    url: "{{ onepassword_repo_key }}"
    dest: "{{ onepassword_repo_key_path }}"
    mode: "0644"
  become: true

- name: onepassword | package repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ onepassword_repo_key_path }}] {{ onepassword_repo_url }} stable main"
    state: present
    filename: 1password
  become: true

- name: onepassword | package
  ansible.builtin.apt:
    update_cache: true
    pkg: "{{ onepassword_cli_package }}"
  become: true
