- name: onepassword | apt key
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    state: present
  become: true

- name: onepassword | package repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://downloads.1password.com/linux/debian/amd64 stable main
    state: present
    filename: 1password
  become: true

- name: onepassword | package
  ansible.builtin.apt:
    update_cache: true
    pkg: "{{ onepassword_cli_package }}"
  become: true
