---
- name: vscode | apt repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: deb
    uris: "{{ vscode_repo_url }}"
    suites: stable
    components: main
    architectures:
      - amd64
      - arm64
      - armhf
    signed_by: "{{ vscode_repo_key }}"
  become: true

- name: vscode | package
  ansible.builtin.apt:
    update_cache: true
    pkg: "{{ vscode_package[ansible_system | lower] }}"
  become: true
