---
- ansible.builtin.include_tasks:
    file: darwin.yml
  when: ansible_system == "Darwin"

- ansible.builtin.include_tasks:
    file: linux.yml
  when: ansible_system == "Linux"

- name: vscode | settings directory
  ansible.builtin.file:
    path: "{{ vscode_settings_path[ansible_system | lower] }}"
    state: directory
    recurse: yes

- name: vscode | settings file
  ansible.builtin.template:
    src: settings.json.j2
    dest: "{{ vscode_settings_path[ansible_system | lower]/{{ vscode_settings_file }}"
    mode: "0664"

- name: vscode | extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  changed_when: false
