---
docker_package:
  darwin:
    - docker
  linux:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

docker_dependencies:
  - ca-certificates
  - curl

docker_obsolete_packages:
  - docker.io
  - docker-compose
  - docker-compose-v2
  - docker-doc
  - podman-docker
  - containerd
  - runc

docker_repo_url: https://download.docker.com/linux/ubuntu
