---
- name: asdf | package
  ansible.builtin.unarchive:
    src: "{{ asdf_package_url }}"
    dest: "{{ asdf_install_directory }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  become: true
