---
- ansible.builtin.include_tasks:
    file: darwin.yml
  when: ansible_system == "Darwin"

- ansible.builtin.include_tasks:
    file: linux.yml
  when: ansible_system == "Linux"

- name: neovim | config directory
  ansible.builtin.file:
    path: "{{ neovim_config_directory }}"
    state: directory
    recurse: true
    mode: '0755'

- name: neovim | autoload directory
  ansible.builtin.file:
    path: "{{ neovim_autoload_directory }}"
    state: directory
    recurse: true
    mode: '0755'

 - name: neovim | autoload
   ansible.builtin.get_url:
     url: "{{ neovim_vim_plug_url }}"
     dest: "{{ neovim_autoload_directory }}"
     mode: "0755"

- name: neovim | init.lua
  ansible.builtin.template:
    src: init.lua.j2
    dest: "{{ neovim_config_directory }}/init.lua"
    mode: "0755"
